image: gcc
before_script:
    - apt-get update --yes
    - apt-get install --yes cmake

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        
test:
    stage: test
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd ..
        - ./SOMCPU -n 10 -i EsamplesData/leucemia_116x14.txt --initialization=r --normalizedistance -x 5 -y 5 -s 0.01 -t

deploy:
  stage: deploy
  script: 
    - docker build -t SOMCPU .