image: gcc

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/mistrello96/somcpu:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/mistrello96/somcpu:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/mistrello96/somcpu

stages: 
    - build
    - test
    - deploy
    - release

build:
    stage: build
    tags:
        - deploy
    script:
        - docker build -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE
        
test:
    stage: test
    tags:
    - deploy
    script:
        - docker run $CONTAINER_TEST_IMAGE "./SOMCPU -n 10 -i EsamplesData/leucemia_116x14.txt --initialization=r --normalizedistance -x 5 -y 5 -s 0.01 -t"
        - docker run $CONTAINER_TEST_IMAGE "./SOMCPU -n -10 -i EsamplesData/leucemia_116x14.txt --initialization=r --normalizedistance -x 5 -y 5 -s -0.01 -t"
        - docker run $CONTAINER_TEST_IMAGE "./SOMCPU -n 10 -i EsamplesData/leucemia_116x14.txt --initialization=r --normalizedistance -x 5 -y 5 -s 0.01 -t"

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

#deploy:
#  stage: deploy

