image: gcc
before_script:
    - apt-get update --yes
    - apt-get install --yes cmake

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 9
        
test:
  stage: test
  script:
    - ./SOMCPU -h
