image: gcc

stages: 
    - build
    - test
    - deploy
    
#before_script:
#    - apt-get update --yes
#    - apt-get install --yes cmake
#    - apt-get install --yes make

build:
    stage: build
    before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes make
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        
test:
    stage: test
    before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes make
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd ..
        - ./SOMCPU -n 10 -i EsamplesData/leucemia_116x14.txt --initialization=r --normalizedistance -x 5 -y 5 -s 0.01 -t

deploy:
  stage: deploy
  image: docker
  script: 
    - docker build -t somcpu .
    - docker run somcpu -h